---
    - name: download nodejs install script
      get_url: url=https://deb.nodesource.com/setup_{{nodeVersion}} dest=./nodeinstall.sh

    - name: install nodejs script
      shell:  sudo -E bash ./nodeinstall.sh

    - name: install nodejs
      become: yes
      become_method: sudo
      apt: name=nodejs update_cache=yes

    - name: update npm
      become: yes
      become_method: sudo
      shell: npm install npm -g

    - name: verify node installation
      shell: node --version

    - name: verify npm installation
      shell: npm --version

    - name: install pm2 globally
      become: yes
      become_method: sudo
      npm: name=pm2 global=yes

